### ISSUE TITLE
Vuls2-based reports cannot be generated in parallel

### ISSUE THREAD

**Issue by m124523** [future-architect/vuls#2178]
# What did you do? (required. The issue will be **closed** when not provided.)
Run multiple instances of `vuls report` on scan results of RedHat-based machines

# What did you expect to happen?
They should run in parallel

# What happened instead?
Vuls2 detection stage is run serially. The bolt DB file is exclusively locked by one process.

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

1. Run `vuls scan` on several machines
2. Run multiple `vuls report` on the reports concurrently.

# Configuration (**MUST** fill this out):

* Go version (`go version`):
```
go version go1.24.2 linux/amd64
```

* Go environment (`go env`):
```
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/var/lib/vuls/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/var/lib/vuls/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1721578707=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/dev/null'
GOMODCACHE='/var/lib/vuls/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/var/lib/vuls/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/var/lib/vuls/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.24.2'
GOWORK=''
PKG_CONFIG='pkg-config'
```

* Vuls environment:

Hash : vuls-0.30.0-358cbf59b8480330cebed319dee1bfc4c5704c7e-2025-03-18T06:42:29Z

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

```toml
[cveDict]
sqlite3Path = "/var/lib/vuls/cve.sqlite3"

[ovalDict]
sqlite3Path = "/var/lib/vuls/oval.sqlite3"

[gost]
sqlite3Path = "/var/lib/vuls/gost.sqlite3"

[kevuln]
sqlite3Path = "/var/lib/vuls/go-kev.sqlite3"

[vuls2]
path = "/var/lib/vuls/go-kev.sqlite3"

[servers]
"x" = { host = "x"}
"y" = { host = "y"}
```

* command:
`vuls report -format-json -results-dir /var/lib/vuls/results/x`
