### ISSUE TITLE
Package query fails on debian based container

### ISSUE THREAD

**Issue by leg100** [future-architect/vuls#519]
# Environment

Kubernetes/Docker/Debian

I'm running vuls in a container, scanning another container, on a kubernetes cluster.

Config:
```toml
[servers]

[servers.localhost]
host = "localhost"
port = "local"

[servers.localhost.containers]
includes = ["target"]
```

Where `target` is the name of the container I'm scanning. It is a debian (wheezy) based container.

## Vuls

Hash : 8e15b9c

## OS
- Target Server: debian container
- Vuls Server: debian container

## Go
- Go version: 1.8

# Current Output

```
[Oct 20 08:03:41] DEBUG [af93ae03c129@localhost] execResult: servername: 
  cmd: docker exec --user 0 af93ae03c129 /bin/bash -c "dpkg-query -W -f='${binary:Package},${db:Status-Abbrev},${Version}\n'"
  exitstatus: 0
  stdout: ,,,,
,,,,
,,,,
,,,,
,,,,
,,,,
,,,,
,,,,
<snip>
,,,,
,,,,
,,,,
,,,,
,,,,
,,,,

  stderr: 
  err: %!s(<nil>)
[Oct 20 08:03:41] DEBUG [localhost] Panic: runtime error: index out of range on af93ae03c129@localhost
```

# Addition Details

## Expected Behavior

List packages in debug logs, and produce a report.

## Actual Behavior

Panic

## Steps to reproduce the behaviour

```
vuls scan -containers-only -debug -config config.toml
```
